# Veil-Miner-SHA (AMD / OpenCL) custom miner package for HiveOS
CUSTOM_NAME=veilminersha
CUSTOM_VERSION=0.1.0
CUSTOM_LOG_BASENAME=/var/log/miner/custom/veilminersha
CUSTOM_CONFIG_FILENAME=/hive/miners/custom/veilminersha/veilminersha.conf
